---
layout: page
title: "Generative AI"
subtitle: "AI in your daily life"
date: "Last updated: 2025-05-05"
---

# Introduction

AI is transforming the way we work, think, and create—but are you making the most of it? Our **Gen AI Workshop Series**, led by Dr. Alexei Karas and Lina Mooren, is designed to help you integrate AI into your daily tasks with **practical, hands-on sessions**. One lunch time a week from now until Week 15, we will be exploring a **new AI use case**—from writing emails and brainstorming ideas to enhancing research, automating workflows, and more. Whether you’re a beginner or already experimenting with AI, these sessions will give you the tools to **work smarter, save time, and boost your creativity**. Sessions will be hybrid—attendees can join in-person or via the Teams link provided in the table below, no sign-ups necessary. We hope to see you there!

# Workshop schedule

::: {#ybcspbkdom style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;"}
```{=html}
<style>#ybcspbkdom table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
&#10;#ybcspbkdom thead, #ybcspbkdom tbody, #ybcspbkdom tfoot, #ybcspbkdom tr, #ybcspbkdom td, #ybcspbkdom th {
  border-style: none;
}
&#10;#ybcspbkdom p {
  margin: 0;
  padding: 0;
}
&#10;#ybcspbkdom .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}
&#10;#ybcspbkdom .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}
&#10;#ybcspbkdom .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}
&#10;#ybcspbkdom .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}
&#10;#ybcspbkdom .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}
&#10;#ybcspbkdom .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}
&#10;#ybcspbkdom .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}
&#10;#ybcspbkdom .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}
&#10;#ybcspbkdom .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}
&#10;#ybcspbkdom .gt_column_spanner_outer:first-child {
  padding-left: 0;
}
&#10;#ybcspbkdom .gt_column_spanner_outer:last-child {
  padding-right: 0;
}
&#10;#ybcspbkdom .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}
&#10;#ybcspbkdom .gt_spanner_row {
  border-bottom-style: hidden;
}
&#10;#ybcspbkdom .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}
&#10;#ybcspbkdom .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}
&#10;#ybcspbkdom .gt_from_md > :first-child {
  margin-top: 0;
}
&#10;#ybcspbkdom .gt_from_md > :last-child {
  margin-bottom: 0;
}
&#10;#ybcspbkdom .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}
&#10;#ybcspbkdom .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}
&#10;#ybcspbkdom .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}
&#10;#ybcspbkdom .gt_row_group_first td {
  border-top-width: 2px;
}
&#10;#ybcspbkdom .gt_row_group_first th {
  border-top-width: 2px;
}
&#10;#ybcspbkdom .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}
&#10;#ybcspbkdom .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}
&#10;#ybcspbkdom .gt_first_summary_row.thick {
  border-top-width: 2px;
}
&#10;#ybcspbkdom .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}
&#10;#ybcspbkdom .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}
&#10;#ybcspbkdom .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}
&#10;#ybcspbkdom .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}
&#10;#ybcspbkdom .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}
&#10;#ybcspbkdom .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}
&#10;#ybcspbkdom .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}
&#10;#ybcspbkdom .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}
&#10;#ybcspbkdom .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}
&#10;#ybcspbkdom .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}
&#10;#ybcspbkdom .gt_left {
  text-align: left;
}
&#10;#ybcspbkdom .gt_center {
  text-align: center;
}
&#10;#ybcspbkdom .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}
&#10;#ybcspbkdom .gt_font_normal {
  font-weight: normal;
}
&#10;#ybcspbkdom .gt_font_bold {
  font-weight: bold;
}
&#10;#ybcspbkdom .gt_font_italic {
  font-style: italic;
}
&#10;#ybcspbkdom .gt_super {
  font-size: 65%;
}
&#10;#ybcspbkdom .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}
&#10;#ybcspbkdom .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}
&#10;#ybcspbkdom .gt_indent_1 {
  text-indent: 5px;
}
&#10;#ybcspbkdom .gt_indent_2 {
  text-indent: 10px;
}
&#10;#ybcspbkdom .gt_indent_3 {
  text-indent: 15px;
}
&#10;#ybcspbkdom .gt_indent_4 {
  text-indent: 20px;
}
&#10;#ybcspbkdom .gt_indent_5 {
  text-indent: 25px;
}
&#10;#ybcspbkdom .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}
&#10;#ybcspbkdom div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
```
+------+--------+--------+-------------+------+----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week | Date   | Day    | Time        | Room | Theme                            | Teams Meeting Link                                                                                                                                                                                                                                          |
+======+========+========+=============+======+==================================+=============================================================================================================================================================================================================================================================+
| 3    | 14 Feb | Friday | 13:10-13:35 | A-21 | Research Question Generation     | [Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_Y2FkM2FmOWEtNzAwOS00MWFkLWI3YjEtODY0MTc5NzNjYTNl%40thread.v2/0?context=%7b%22Tid%22%3a%2263817156-fe48-40a1-8277-19db53d4dc59%22%2c%22Oid%22%3a%22990a9d0c-2360-44a5-a12a-7400af696e17%22%7d) |
+------+--------+--------+-------------+------+----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 8    | 28 Mar | Friday | 13:10-13:35 | A-21 | Writing in Collaboration with AI | [Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZjExNWYyMjUtYmU3OS00NjZmLWIwNTYtZmVjMDk4ODM5NDJh%40thread.v2/0?context=%7b%22Tid%22%3a%2263817156-fe48-40a1-8277-19db53d4dc59%22%2c%22Oid%22%3a%22990a9d0c-2360-44a5-a12a-7400af696e17%22%7d) |
+------+--------+--------+-------------+------+----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9    | 4 Apr  | Friday | 13:10-13:35 | A-21 | Marketing with AI                | [Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZGExYTEyNDEtOTdlOS00NDdhLWE2ZDQtNjEyODdhNDZiNTg3%40thread.v2/0?context=%7b%22Tid%22%3a%2263817156-fe48-40a1-8277-19db53d4dc59%22%2c%22Oid%22%3a%22990a9d0c-2360-44a5-a12a-7400af696e17%22%7d) |
+------+--------+--------+-------------+------+----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 13   | 2 May  | Friday | 13:10-13:35 | A-21 | Exam Question Generation         | [Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MTMxODBlNmItMjVkOS00Yzg2LTg4MzMtNWFjMTE2Yzc3ZDAy%40thread.v2/0?context=%7b%22Tid%22%3a%2263817156-fe48-40a1-8277-19db53d4dc59%22%2c%22Oid%22%3a%22990a9d0c-2360-44a5-a12a-7400af696e17%22%7d) |
+------+--------+--------+-------------+------+----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14   | 9 May  | Friday | 13:10-13:35 | A-21 | Notebook LM                      | [Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NjE2MGVjYzAtNjA2ZS00ODIzLWFiN2MtZGRhZDYxMmU5NTVm%40thread.v2/0?context=%7b%22Tid%22%3a%2263817156-fe48-40a1-8277-19db53d4dc59%22%2c%22Oid%22%3a%22990a9d0c-2360-44a5-a12a-7400af696e17%22%7d) |
+------+--------+--------+-------------+------+----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 15   | 16 May | Friday | 13:10-13:35 | A-21 | TBA                              | [Link]()                                                                                                                                                                                                                                                    |
+------+--------+--------+-------------+------+----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::
