---
layout: page
title: "Data Center Apprenticeships"
---

The Data Center Apprenticeship program is designed to help faculty and staff integrate data science and AI tools into teaching, research, and administrative processes. Students work together with UCR a member of faculty or staff to develop ways to incorporate data science tools into the UCR curriculum, faculty research, or university-wide administrative processes.

Apprenticeship programs take place in January and June, and consist of a 2-week intensive training program tailored to the needs of the projects that the apprentices will be working on. The participating students are expected to attend these workshops, and have until the end of the following semester to complete their projects; participation in the Apprenticeship program counts as an academic internship and earns students one course's worth of credits (7.5 ECTS).

**For faculty and staff:** If you have a project idea that could benefit from the help of a data science apprentice, please consider responding to the call for project proposals that we send out in the first half of the semester.

**For students:** If you're interested in becoming an apprentice, please email us at [datacenter\@ucr.nl](datacenter@ucr.nl), describing your academic background and the kinds of projects you would be interested in.

# 2025 January

The January 2025 Apprenticeship program is now running! All are welcome to join our daily workshops. You can access the schedule and workshop materials [here](apprenticeship/apprenticeship_2025h1.md).

# 2024 June

After a successful pilot, the second iteration of the Apprenticeship program took place in June 2024. Our apprentices support two data encounters and an interdisciplinary research project. They will continue to work on their projects in the Fall 2024 semester. You can access all workshop materials [here](apprenticeship/apprenticeship_2024h2.md).

# 2024 January

The first iteration of the Apprenticeship program took place in January 2024. Our six apprentices worked on a wide range of projects, including data encounters, UCR marketing efforts, and a faculty research project. Read more about the projects and access all workshop materials [here](apprenticeship/apprenticeship_2024h1.md).
