---
layout: page
title: "Contact us"
---

The Data Center student fellows hold office hours in the Data Center’s office (Anne ground floor) to answer questions and help with assignments. Drop by to office hours if you’re looking for some data science help, whether for a data encounter in a course, another UCR course, or your SEPR!

# Office hour schedule

Office hours are held in the Data Center’s office (Anne ground floor), every week during the semester between week 4 and week 15. You are welcome to drop by any time during the office hours, no appointment needed.

Office hours are with the current Data Center interns; you can learn more about their specific expertise below the schedule.

```{=html}
```
|             | Monday  | Tuesday | Wednesday | Thursday |  Friday  |
|:-----------:|:-------:|:-------:|:---------:|:--------:|:--------:|
| 9:00-10:00  |         |         |           |          |          |
| 10:00-11:00 |         |         |           |  Michel  |          |
| 11:00-12:00 |  Julia  |         |           |          |   Lili   |
| 12:00-13:00 |         |         |           |          | Gabriela |
| 13:00-14:00 |         |         |           |          |          |
| 14:00-15:00 |         |  Mare   |           |          |          |
| 15:00-16:00 |         |         |  Michel   |          |          |
| 16:00-17:00 | Clement |         |           |          |          |
| 17:00-18:00 | Michel  |         |           |          |          |
| 18:00-19:00 |         |         |           |          |          |

-   **Clement:** Spatial data, rasters, maps, Ecology
-   **Gabriela:** R, Python, Stata, SQL (soon), statistics, visualization, data tidying and transformation, data import/export, spatial data
-   **Julia:** R, data cleaning and wrangling, data visualization, statistics
-   **Lili:** R, text analysis, character strings
-   **Mare:** Basic R and Python; Working with Corpora / Text analysis
-   **Michel:** Data Science in R: Data wrangling, spatial data, data visualizations and simple text analysis

# Contact us

If you would like to request an individual consultation, or would like to know more about becoming an intern for the Data Center, feel free to send an email to [datacenter\@ucr.nl](mailto:datacenter@ucr.nl){.email}.

Make sure to check this website for news and updates, and follow us on Instagram!
