---
layour: page
title: "Useful links"
date: "Last updated: 2024-06-12"
output:
  md_document:
    variant: gfm
    preserve_yaml: true
---

You’ll work on different assignments in different courses, but some general resources for working with R can be helpful in a wide range of assignments. Below are some helpful links in case you would like to complement the Data Center workshops and tutorials (which you can find on the Tutorials page and the individual course pages).

*If you have suggestions for adding more resources, please email us at [datacenter\@ucr.nl](mailto:datacenter@ucr.nl){.email}.*

# The basics of R

-   [A (very) short introduction to R](https://github.com/ClaudiaBrauer/A-very-short-introduction-to-R/blob/master/documents/A%20(very)%20short%20introduction%20to%20R.pdf)
-   [Cheat sheet for importing data](https://github.com/rstudio/cheatsheets/blob/main/data-import.pdf)
-   [Cheat sheet for data manipulation](https://github.com/rstudio/cheatsheets/blob/main/data-transformation.pdf) (including `filter()`, `select()` and the pipe operator(`%>%`))
-   [Cheat sheet for data tidying](https://github.com/rstudio/cheatsheets/blob/main/tidyr.pdf) (including reshaping and pivoting)
-   [Getting started with Data in R](https://moderndive.netlify.app/1-getting-started.html#getting-started) (covers: using R and RStudio, basic terminology, introduction to packages)
-   [R objects](https://rstudio-education.github.io/hopr/r-objects.html)
-   [Advice on using projects](https://r4ds.had.co.nz/workflow-projects.html)
-   [Full tutorial on R language basics (slides)](https://raw.githack.com/uo-ec607/lectures/master/04-rlang/04-rlang.html#1)
-   [Full tutorial on data cleaning and wrangling (slides)](https://raw.githack.com/uo-ec607/lectures/master/05-tidyverse/05-tidyverse.html#1)
-   [More explanation on the pipe operator](https://r4ds.had.co.nz/pipes.html)
-   [Selecting and filtering data](https://mdsr-book.github.io/mdsr2e/ch-dataI.html#sec:pipe)
-   [Creating a project in RStudio (video)](https://www.youtube.com/watch?v=WyrJmJWgPiU)
-   [Packages in R (video)](https://www.youtube.com/watch?v=v6VygIgvoZU&t=1s)
-   [Loading a data file (video)](https://www.youtube.com/watch?v=2MVolYETR5Q)
-   [Data manipulation (video)](https://www.youtube.com/watch?v=Zc_ufg4uW4U)

# Help with `ggplot`

-   [Cheat sheet for `ggplot`](https://github.com/rstudio/cheatsheets/blob/main/data-visualization-2.1.pdf)
-   [The R Graph Gallery (example plots, including full R scripts)](https://www.r-graph-gallery.com/)
-   [How to make any plot in ggplot2?](http://r-statistics.co/ggplot2-Tutorial-With-R.html#6.1%20Make%20a%20time%20series%20plot%20(using%20ggfortify))
-   [More details on data visualization](https://mdsr-book.github.io/mdsr2e/ch-vizII.html#a-grammar-for-data-graphics)
-   [Saving plots with `ggsave()`](https://www.tutorialgateway.org/save-r-ggplot-using-ggsave/)
-   [Basic `ggplot` tutorial (video)](https://www.youtube.com/watch?v=hr2X7rmkprM)
-   [Customizing plots (video)](https://www.youtube.com/watch?v=1GmQ5BdAhG4)

# Importing data

-   [Cheat sheet for data import](https://github.com/rstudio/cheatsheets/blob/main/data-import.pdf)
-   [More on `read_csv()`](https://uomresearchit.github.io/r-tidyverse-intro/03-loading-data-into-R/)
-   [Import with `haven`](https://tutorials.methodsconsultants.com/posts/reading-sas-spss-or-stata-files-into-r-using-haven/)
-   [Import with `readr` and `readxl` (video)](https://www.youtube.com/watch?v=366N1K1ja8g)
-   [Import using `haven` (video)](https://www.youtube.com/watch?v=egFoDj6H9Ts)

# Data cleaning

-   [Filter, select, mutate and summarize data](https://rpubs.com/AnalystNyamu/507453)
-   [More on `mutate()`](https://www.sharpsightlabs.com/blog/mutate-in-r/)
-   [Summarizing data by groups](https://r-graphics.org/recipe-dataprep-summarize)
-   [List of common useful functions within `summarize()`](https://www.r-bloggers.com/2021/06/summarize-in-r-data-summarization-in-r/)
-   [More on `rename()`](https://www.datasciencemadesimple.com/rename-the-column-name-in-r-using-dplyr/)
-   [How to handle missing data](https://universeofdatascience.com/how-to-handle-missing-values-in-r/)
-   [Conversions between long and wide format](https://mdsr-book.github.io/mdsr2e/ch-dataII.html#data-verbs-for-converting-wide-to-narrow-and-vice-versa)
-   [Select, filter, mutate and summarize data (video)](https://www.youtube.com/watch?v=nRtp7wSEtJA)
-   [Summarizing by groups (video)](https://www.youtube.com/watch?v=zAlbrPozMHI)
-   [How to handle missing values (video)](https://www.youtube.com/watch?v=O_gPPrezk5o)

# Merging data

-   [`bind_rows()` and join functions visualized](https://www.r4epi.com/working-with-multiple-data-frames.html)
-   [More on join functions](https://www.datasciencemadesimple.com/join-in-r-merge-in-r/)
-   [Examples of using joins](https://statisticsglobe.com/r-dplyr-join-inner-left-right-full-semi-anti)
-   [Visualization of joining datasets](https://www.garrickadenbuie.com/project/tidyexplain/#mutating-joins)
-   [More on join functions (video)](https://www.youtube.com/watch?v=Yg-pNqzDuN4)

# Geospatial data

-   Cornell University Computing for Information Science materials:

    -   [Introduction to geospatial visualization](https://info5940.infosci.cornell.edu/notes/geoviz/intro-geospatial-viz/)
    -   [Drawing raster maps with ggmap](https://info5940.infosci.cornell.edu/notes/geoviz/raster-maps-with-ggmap/)
    -   [Practice drawing raster maps](https://info5940.infosci.cornell.edu/notes/geoviz/raster-maps-practice/)
    -   [Importing spatial data files using sf](https://info5940.infosci.cornell.edu/notes/geoviz/simple-features/)
    -   [Drawing vector maps with simple features and ggplot2](https://info5940.infosci.cornell.edu/notes/geoviz/vector-maps/)
    -   [Practice drawing vector maps](https://info5940.infosci.cornell.edu/notes/geoviz/vector-maps-practice/)

# Text analysis

-   [Text mining with R: A tidy approach](https://www.tidytextmining.com/)
-   [Regular expression cheat sheet](https://evoldyn.gitlab.io/evomics-2018/ref-sheets/R_strings.pdf)
-   [Interactive tidytext tutorial](https://juliasilge.shinyapps.io/learntidytext/#section-introduction)

# Other

-   [The Big Book of R](https://www.bigbookofr.com/): huge list of R resources
-   [adventr](https://www.statisticsadventure.com/adventr/): R tutorial from the author of Discovering Statistics Using IBM SPSS Statistics (ACCRMET101 level)
-   [discovr](https://www.discovr.rocks/discovr/): R tutorial from the author of Discovering Statistics Using IBM SPSS Statistics (SSCRMET201 level)
