{
  "hash": "3a8281d01297cfd41fbba1939bcd9c33",
  "result": {
    "engine": "knitr",
    "markdown": "---\nlayout: page\ntitle: \"SCIBIOM303 Workshop 2: Temperature and Heatstroke-related Ambulance Dispatches\"\nsubtitle: \"Spring 2025\"\ndate: \"Last updated: 2025-08-17\"\n---\n\n\n\n\n# Introduction\n\nIn this encounter, we will explore the relationship between temperature and heatstroke-related ambulance dispatches using data from Japan. The data contains daily records of maximum temperature and relative humidity across all 47 prefectures from 2015 to 2019.\n\n# Loading packages\n\nWe will start by loading the tidyverse and rio packages. Ensure these packages are installed before running the code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"tidyverse\")\n# install.packages(\"rio\")\nlibrary(tidyverse)\nlibrary(rio)\n```\n:::\n\n\n# Importing Data\n\nWe will import two data sets: one for heatstroke-related ambulance dispatches (HSAD) and one for temperature data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhsad <- import(\"https://github.com/ucrdatacenter/projects/raw/refs/heads/main/SCIBIOM303/2025h1/data/HSAD.csv\")\ntemp <- import(\"https://github.com/ucrdatacenter/projects/raw/refs/heads/main/SCIBIOM303/2025h1/data/temperature.csv\")\n```\n:::\n\n\n# Merging the Data\n\nTo analyze the relationship between temperature and heatstroke-related ambulance dispatches, we will merge the two data sets using the left_join() function. We will join them on the columns Date and Prefecture. Next, we convert the Date column into a date format.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmerged <- left_join(temp, hsad, by = c(\"Date\", \"Prefecture\")) |> \n  mutate(Date = dmy(Date)) \n```\n:::\n\n\n# Analyzing Data for a Specific Prefecture and Year\n\nWe will focus on Hiroshima in 2015 to study the relationship between daily maximum temperature and heatstroke-related ambulance dispatches.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhiroshima_2015 <- merged |> \n  filter(Prefecture == \"Hiroshima\") |> \n  filter(Year == 2015)\n```\n:::\n\n\n# Visualizing the Data\n\nWe will create a scatter plot to visualize the relationship between maximum temperature and heatstroke-related ambulance dispatches. A trend line is added to show the overall pattern.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(hiroshima_2015, aes(x = Tempmax, y = HSAD)) +\n  geom_point() +\n  geom_smooth(se = FALSE) +\n  labs(title = \"Temperature and Heatstroke-related Ambulance Dispatches in Hiroshima in 2015\",\n       x = \"Maximum Temperature\",\n       y = \"Heatstroke-related Ambulance Dispatches\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](workshop2_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThe number of heatstroke-related ambulance dispatches increases significantly when the temperature exceeds 30°C. This trend aligns with what we expect because higher temperatures can cause a rapid rise in core body temperature, leading to heatstroke ([source](https://www.mayoclinic.org/diseases-conditions/heat-stroke/symptoms-causes/syc-20353581)).\n\n# Trends Over Time\n\nWe will create another plot to show how maximum temperature changes over time in Hiroshima in 2015.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(hiroshima_2015, aes(x = Date, y = Tempmax)) +\n  geom_point() +\n  geom_smooth(se = FALSE) +\n  labs(title = \"Temperature Over Time in Hiroshima in 2015\",\n       x = \"Date\",\n       y = \"Maximum Temperature\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](workshop2_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThe temperature rises in June, peaks in August (above 35°C), and then decreases in October. This seasonal pattern is typical for Hiroshima ([source](https://www.climatestotravel.com/climate/japan/hiroshima)).\n\n# Linear Regression Analysis\n\nTo quantify the relationship between temperature and heatstroke-related ambulance dispatches, we perform a linear regression analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlr <- lm(HSAD ~ Tempmax, data = hiroshima_2015)\nsummary(lr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = HSAD ~ Tempmax, data = hiroshima_2015)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-18.947  -5.163  -1.816   3.845  27.511 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -80.4723     6.5532  -12.28   <2e-16 ***\nTempmax       3.1151     0.2248   13.86   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.083 on 118 degrees of freedom\nMultiple R-squared:  0.6193,\tAdjusted R-squared:  0.6161 \nF-statistic:   192 on 1 and 118 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe R-squared value of 0.6193 indicates that about 61.93% of the variability in ambulance dispatches can be explained by the maximum temperature. This suggests a strong positive relationship between HSAD and temperature.\n\n# Comparing Two Prefectures\n\nNext, we will compare the relationship between temperature and ambulance dispatches in Hiroshima and Kyoto in 2015 using a line graph.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmerged |> \n  filter(Prefecture == \"Kyoto\"| Prefecture == \"Hiroshima\") |> \n  filter(Year == 2015) |> \n  ggplot() +\n  geom_smooth(aes(x = Tempmax, y = HSAD, color = Prefecture), se = FALSE) +\n  labs(title = \"Temperature and Heatstroke-related Ambulance Dispatches (2015)\",\n       x = \"Maximum Temperature\",\n       y = \"Heatstroke-related Ambulance Dispatches\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](workshop2_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nBoth prefectures show similar trends, with the number of dispatches increasing as temperature rises ([source](https://doi.org/10.3961/jpmph.2012.45.5.309)).\n\n# Dispatches by Day of the Week\n\nWe can also analyze the average number of dispatches by the day of the week.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhiroshima_2015 |>\n  group_by(Dow) |>\n  summarize(HSAD = mean(HSAD)) |>\n  ggplot(aes(x = Dow, y = HSAD)) +\n  geom_col() +\n  labs(title = \"Heatstroke-related Ambulance Dispatches by Day of the Week (2015)\",\n       x = \"Day of the week\",\n       y = \"Heatstroke-related Ambulance Dispatches\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](workshop2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThere are more dispatches on days 1 and 7, which correspond to Sunday and Saturday, respectively. This is expected, as heatstroke cases are more frequent on weekends, especially on Sundays when people engage in outdoor or sporting activities ([source](https://www.channelnewsasia.com/today/ground-up/heatstroke-heat-related-illnesses-dangers-risks-take-precautions-misconceptions-4647621)).\n\n# Creating the Heat Index\n\nThe heat index, also known as the \"feels-like\" temperature, is calculated using temperature and humidity to reflect how hot it feels to the human body. This formula was developed by Robert G. Steadman in 1979 and later adapted by the National Weather Service. It accounts for the reduced ability of the body to cool itself through sweating in high-humidity conditions, making it a crucial indicator for heat-related health risks ([source](https://www.weather.gov/ama/heatindex)).\n\nWe first convert the temperature to Fahrenheit to calculate the heat index, then convert it back to Celsius.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhiroshima_lr_data <- hiroshima_2015 %>%\n  mutate(\n    Temp_F = Tempmax * 9 / 5 + 32,\n    Heat_Index_F = -42.379 + \n      2.04901523 * Temp_F + \n      10.14333127 * Rhumave - \n      0.22475541 * Temp_F * Rhumave - \n      0.00683783 * Temp_F^2 - \n      0.05481717 * Rhumave^2 + \n      0.00122874 * Temp_F^2 * Rhumave + \n      0.00085282 * Temp_F * Rhumave^2 - \n      0.00000199 * Temp_F^2 * Rhumave^2,\n    Heat_Index_C = (Heat_Index_F - 32) * 5 / 9)\n```\n:::\n\n\n# Visualizing Heat Index and Ambulance Dispatches\n\nWe will create a plot to show the relationship between the heat index and ambulance dispatches.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(hiroshima_lr_data, aes(x = Heat_Index_C, y = HSAD)) +\n  geom_point() +\n  geom_smooth(se = FALSE) +\n  labs(title = \"Heat Index and Heatstroke-related Ambulance Dispatches in Hiroshima in 2015\",\n       x = \"Heat Index\",\n       y = \"Heatstroke-related Ambulance Dispatches\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](workshop2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nThe number of dispatches rises sharply after the heat index exceeds 30°C, confirming that the heat index is a strong predictor of heat-related emergencies ([source](https://doi.org/10.1186/s40779-015-0056-z)).\n\n# Linear Regression with Heat Index\n\nFinally, we perform a linear regression analysis using the heat index to predict ambulance dispatches.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlr2 <- lm(HSAD ~ Heat_Index_C, data = hiroshima_lr_data)\nsummary(lr2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = HSAD ~ Heat_Index_C, data = hiroshima_lr_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-16.4816  -4.0284  -0.9406   3.2193  21.7201 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -45.3048     3.2060  -14.13   <2e-16 ***\nHeat_Index_C   1.6585     0.0947   17.51   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.905 on 118 degrees of freedom\nMultiple R-squared:  0.7222,\tAdjusted R-squared:  0.7198 \nF-statistic: 306.8 on 1 and 118 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe R-squared value is 0.7222, meaning that 72.22% of the variability in dispatches can be explained by the heat index. This suggests the heat index is an even stronger predictor than temperature alone.\n",
    "supporting": [
      "workshop2_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}