---
layout: page
title: "SCIBIOM303 Workshop 1: Introduction to R"
subtitle: "Spring 2025"
date: "Last updated: `r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, error=FALSE)
```

The data encounter in this course has three components. First, you'll follow a series of general tutorials that present the R skills you'll need for the course. Second, you'll learn how to apply these skills to a specific case study related to the course content. Then, you apply the same skills to a new dataset in a group project.

As preparation for the workshop, you have learned to:

1.  [install R](../../../tutorials/r_install)
2.  [find your way around R and RStudio](../../../tutorials/r_basics)

The first workshop will cover the following topics (each topic links to a separate tutorial with additional details and a video explanation):

1.  [Objects and functions](../../../tutorials/r_objects)
2.  [Data wrangling: filtering rows and selecting columns](../../../tutorials/r_intro_subset)
3.  [Data wrangling: creating new variables](../../../tutorials/r_intro_mutate)
4.  [Data wrangling: summarizing data (within groups)](../../../tutorials/r_intro_summarize)
5.  [The tidy workflow](../../../tutorials/r_intro_pipe)
6.  [Data visualization: introduction to `ggplot`](../../../tutorials/r_ggplot_intro)
7.  [Data visualization: relationships between variables](../../../tutorials/r_ggplot_bivariate)
8.  [Statistics in R](../../../tutorials/r_stats) (only the section on linear regression is needed for the course)

In addition, the Data Center maintains a list of [useful resources](../../../tutorials/links) with additional tutorials and references.
