---
title: "SCIENVI"
date: "Spring 2023<br>Last updated: `r Sys.Date()`"
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

\

# Introduction

This page collects workshop materials, data sources and supplementary materials for the data-driven assignments in the Spring 2023 edition of Ecology at UCR. You can also access the related files directly on [Github](https://github.com/ucrdatacenter/projects).

If you have any questions related to the assignment do not hesitate to reach Jennifer or Bianka during Data Center office hours held every Tuesday from 11:30 to 13:30 in the pre-med space in Eleanor. There is no need to sign up in advance to join. If this time is inconvenient for you feel free to write Jennifer or Bianka an email ([ucrdatacenter\@ucr.nl](mailto:ucrdatacenter@ucr.nl){.email}) to schedule an individual meeting.

\

# Simple Assignment

The simple assignment is an initial workshop in R where you follow the instructions and codes given to you on the website to get yourself familiar with R. This assignment is compulsory, therefore, everyone has to complete it. The instructions for the simple assignment can be found here:

-   [Simple assignment in SCIENVI201](SCIENVI_2023h1/SCIENVI201/Simple_Assignment.html).\
-   [Simple assignment in SCIENVI303](SCIENVI_2023h1/SCIENVI303/Simple_Assignment.html).

# Research Assignment

If you decide to conduct your research assignment in R (and we hope you do), you can find the instructions here:

-   [Research Assignment](SCIENVI_2023h1/Research_Assignment.html).
