---
title: "SSCECON207<br>International Macroeconomics<br>Spring 2022"
date: "Last updated: `r Sys.Date()`"
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
---

# Introduction

This page collects workshop materials, data sources and supplementary materials for the data-driven assignments in the Spring 2022 edition of International Macroeconomics at UCR. You can also access the related files directly on [Github](https://github.com/ucrdatacenter/projects/tree/main/SSCECON207/2022h1).

# Working with R and RStudio

## Installing R and RStudio

R is the programming language that you use when working with data. RStudio is a development environment that makes working with R much more convenient. Both are free to download and install.

To download R, go to [cloud.r-project.org](https://cloud.r-project.org/) and follow the instructions on the page. To download RStudio, go to [rstudio.com/products/rstudio/download](https://www.rstudio.com/products/rstudio/download/), scroll down and download the file recommended for your operating system.

When installing, you can always stick to the default settings, unless you have different preferences.

In case you get stuck at any point, or would like more guidance in the installation process, feel free to check out any of the following links:

-   [Tutorial: Getting Started with R and RStudio](https://www.dataquest.io/blog/tutorial-getting-started-with-r-and-rstudio/)
-   [R Tutorial: How to install R and R studio (video)](https://www.youtube.com/watch?v=0Qu7Jg1Jw5A)

# Assignments

## Timeline

-   The first Data Center workshop takes place in week 2. It covers the basics of how to create figures in R. You should make sure to have R and RStudio installed before this workshop, and read sections 2, 3.1-3.4, and 4-6 of [A (very) short introduction to R](https://github.com/ClaudiaBrauer/A-very-short-introduction-to-R/blob/master/documents/A%20(very)%20short%20introduction%20to%20R.pdf) and sections 1-4 of [How to make any plot in ggplot2?](http://r-statistics.co/ggplot2-Tutorial-With-R.html#6.1%20Make%20a%20time%20series%20plot%20(using%20ggfortify)).
-   The IS-LM poster assignment is due in week 4 of the semester.
-   The second Data Center workshop takes place in week 7. It builds on your existing R skills, with a focus on finding and cleaning data.
-   The final empirical paper is due at the end of week 15.
-   The Data Center student fellows hold office hours every Wednesday between 15:00-19:00 (15:00-17:00 with Tina, 17:00-19:00 with Bianka) in the Data Center's office (Anne 1.30 - first floor) to answer questions and help with the poster and paper assignments. Feel free to email Tina ([datacenter\@ucr.nl](mailto:datacenter@ucr.nl){.email}) to schedule an individual consultation outside of office hours or to attend office hours. In case you would like to make use of the in-person office hours, please email the Data Center at least two hours in advance.

## IS-LM poster

### Guidelines

The assignment guidelines and the grading rubric are on Moodle.

### Workshop handout

The materials covered in the first Data Center workshop, including both code and explanations, can be found [here](SSCECON207_2022h1/workshop1.html).

### Supporting materials

#### The basics of R

-   [Cheat sheet for importing data](https://github.com/rstudio/cheatsheets/blob/main/data-import.pdf)
-   [Cheat sheet for data manipulation](https://github.com/rstudio/cheatsheets/blob/main/data-transformation.pdf) (including `filter()`, `select()` and the pipe operator(`%>%`))
-   [Cheat sheet for data tidying](https://github.com/rstudio/cheatsheets/blob/main/tidyr.pdf) (including reshaping and pivoting)
-   [Getting started with Data in R](https://moderndive.netlify.app/1-getting-started.html#getting-started) (covers: using R and RStudio, basic terminology, introduction to packages)
-   [R objects](https://rstudio-education.github.io/hopr/r-objects.html)
-   [Advice on using projects](https://r4ds.had.co.nz/workflow-projects.html)
-   [Full tutorial on R language basics (slides)](https://raw.githack.com/uo-ec607/lectures/master/04-rlang/04-rlang.html#1)
-   [Full tutorial on data cleaning and wrangling (slides)](https://raw.githack.com/uo-ec607/lectures/master/05-tidyverse/05-tidyverse.html#1)
-   [More explanation on the pipe operator](https://r4ds.had.co.nz/pipes.html)
-   [Selecting and filtering data](https://mdsr-book.github.io/mdsr2e/ch-dataI.html#sec:pipe)
-   [Conversions between long and wide format](https://mdsr-book.github.io/mdsr2e/ch-dataII.html#data-verbs-for-converting-wide-to-narrow-and-vice-versa)
-   [Creating a project in RStudio (video)](https://www.youtube.com/watch?v=WyrJmJWgPiU)
-   [Packages in R (video)](https://www.youtube.com/watch?v=v6VygIgvoZU&t=1s)
-   [Loading a data file (video)](https://www.youtube.com/watch?v=2MVolYETR5Q)
-   [Data manipulation (video)](https://www.youtube.com/watch?v=Zc_ufg4uW4U)

#### Help with `ggplot`

-   [Cheat sheet for `ggplot`](https://github.com/rstudio/cheatsheets/blob/main/data-visualization-2.1.pdf)
-   [The R Graph Gallery (example plots, including full R scripts)](https://www.r-graph-gallery.com/)
-   [More details on data visualization](https://mdsr-book.github.io/mdsr2e/ch-vizII.html#a-grammar-for-data-graphics)
-   [Saving plots with `ggsave()`](https://www.tutorialgateway.org/save-r-ggplot-using-ggsave/)
-   [Basic `ggplot` tutorial (video)](https://www.youtube.com/watch?v=hr2X7rmkprM)
-   [Customizing plots (video)](https://www.youtube.com/watch?v=1GmQ5BdAhG4)

#### Data sources used

-   GDP: [World Bank DataBank: GDP (constant LCU)](https://data.worldbank.org/indicator/NY.GDP.MKTP.KN)
-   Consumption: [World Bank DataBank: Final consumption expenditure (constant LCU)](https://data.worldbank.org/indicator/NE.CON.TOTL.KN)
-   Investment: [World Bank DataBank: Gross fixed capital formation (constant LCU)](https://data.worldbank.org/indicator/NE.GDI.FTOT.KN)
-   Government spending: [World Bank DataBank: General government final consumption expenditure (constant LCU)](https://data.worldbank.org/indicator/NE.CON.GOVT.KN)
-   Interest rate: [World Bank DataBank: Real interest rate (%)](https://data.worldbank.org/indicator/FR.INR.RINR)
-   Inflation rate: [World Bank DataBank: Inflation, consumer prices (annual %)](https://data.worldbank.org/indicator/FP.CPI.TOTL.ZG)

## Empirical paper on growth

### Guidelines

The assignment guidelines and the grading rubric are on Moodle.

You can find an example paper [here](https://github.com/ucrdatacenter/projects/raw/main/SSCECON207/2022h1/workshop%202/example%20paper.pdf).

### Workshop handout

The materials covered in the second Data Center workshop, including both code and explanations, can be found [here](SSCECON207_2022h1/workshop2.html).

### Supporting materials

#### Inspiration for your research question

-   [Growthecon](https://growthecon.com/topics/): collections of materials related to various themes related to growth
-   [Conversable Economist](https://conversableeconomist.wpcomstaging.com/): blog connecting current issues to economics
-   [The Economy textbook](https://www.core-econ.org/the-economy/book/text/0-3-contents.html): undergraduate textbook with a focus on growth from multiple aspects. Most relevant units:
    -   [Unit 1](https://www.core-econ.org/the-economy/book/text/01.html) *The capitalist revolution*: introduction to modern growth
    -   [Unit 2](https://www.core-econ.org/the-economy/book/text/02.html) *Technology, population, and growth*: historical perspective on growth
    -   [Unit 20](https://www.core-econ.org/the-economy/book/text/20.html) *Economics of the environment*: connections between growth and climate change; see e.g. figure [20.25](https://www.core-econ.org/the-economy/book/text/20.html#figure-20-25a)
-   [CORE Insight on inequality](https://www.core-econ.org/insights/a-world-of-differences/text/01.html)
-   [Doing economics: Measuring wellbeing](https://www.core-econ.org/doing-economics/book/text/04-01.html): practical instructions to an empirical project using R; other chapters might also be of interest
-   [Our World in Data on economic growth](https://ourworldindata.org/economic-growth)
-   [The World Bank Data Blog](https://www.worldbank.org/en/programs/icp/brief/data-blog)
-   [IMF blog](https://blogs.imf.org/)
-   [Econlife](https://econlife.com/): blog connecting current events, history, and economics
-   [The Economic Historian](https://economic-historian.com/): blog on economic history
-   [American Economic Association Research Highlights](https://www.aeaweb.org/research)

#### Useful data sources

-   [Our World in Data](https://ourworldindata.org/): open-access data source for a wide range of indicators
-   [World Bank Open Data](https://data.worldbank.org/): open-access data source related to development and growth
-   [Gapminder](https://www.gapminder.org/data/): open-access data source related to development and growth; all World Development Indicators also available here
-   [OECD data](https://data.oecd.org/): open-access data source primarily on advanced economies
-   [Maddison Historical Statistics](https://www.rug.nl/ggdc/historicaldevelopment/maddison/?lang=en): GDP per capita and population data for 169 countries between 1000--2018
-   [Total Economy Database](https://www.conference-board.org/data/economydatabase/total-economy-database-productivity): data on GDP and labour statistics for 131 countries (available after creating a free account)
-   [FRED (US Federal Reserve)](https://fred.stlouisfed.org/tags/series): mostly US economic data
-   [Eurostat](https://ec.europa.eu/eurostat/web/main/home): European Union data

#### Additional support with R

Next to the links below, please check out the supporting materials provided for the first Data Center workshop.

*Importing data*

-   [Cheat sheet for data import](https://github.com/rstudio/cheatsheets/blob/main/data-import.pdf)
-   [More on `read_csv()`](https://uomresearchit.github.io/r-tidyverse-intro/03-loading-data-into-R/)
-   [Import with `haven`](https://tutorials.methodsconsultants.com/posts/reading-sas-spss-or-stata-files-into-r-using-haven/)
-   [Import with `readr` and `readxl` (video)](https://www.youtube.com/watch?v=366N1K1ja8g)
-   [Import using `haven` (video)](https://www.youtube.com/watch?v=egFoDj6H9Ts)

*Data cleaning*

-   [Filter, select, mutate and summarize data](https://rpubs.com/AnalystNyamu/507453)
-   [More on `mutate()`](https://www.sharpsightlabs.com/blog/mutate-in-r/)
-   [Summarizing data by groups](https://r-graphics.org/recipe-dataprep-summarize)
-   [List of common useful functions within `summarize()`](https://www.r-bloggers.com/2021/06/summarize-in-r-data-summarization-in-r/)
-   [More on `rename()`](https://www.datasciencemadesimple.com/rename-the-column-name-in-r-using-dplyr/)
-   [How to handle missing data](https://universeofdatascience.com/how-to-handle-missing-values-in-r/)
-   [Select, filter, mutate and summarize data (video)](https://www.youtube.com/watch?v=nRtp7wSEtJA)
-   [Summarizing by groups (video)](https://www.youtube.com/watch?v=zAlbrPozMHI)
-   [How to handle missing values (video)](https://www.youtube.com/watch?v=O_gPPrezk5o)

*Merging data*

-   [`bind_rows()` and join functions visualized](https://www.r4epi.com/working-with-multiple-data-frames.html)
-   [More on join functions](https://www.datasciencemadesimple.com/join-in-r-merge-in-r/)
-   [Examples of using joins](https://statisticsglobe.com/r-dplyr-join-inner-left-right-full-semi-anti)
-   [More on join functions (video)](https://www.youtube.com/watch?v=Yg-pNqzDuN4)
