---
title: "SSCECON209<br>Money, Banking and Finance<br>Spring 2022"
date: "Last updated: `r Sys.Date()`"
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

# Introduction

This page collects helpful links for the banking dashboard assignment in the Spring 2022 edition of Money, Banking and Finance.

If you have questions related to the dashboard assignment or need some help, feel free to join Data Center office hours with Tina (held every Wednesday between 15:00-17:00 in the Data Center's office (Anne 1.30 - first floor). Feel free to email Tina ([datacenter\@ucr.nl](mailto:datacenter@ucr.nl){.email}) to schedule an individual consultation outside of office hours or to attend office hours. In case you would like to make use of the in-person office hours, please email the Data Center at least two hours in advance.

# Example dashboard

You can download a basic example of a banking dashboard by clicking [here](https://github.com/ucrdatacenter/projects/raw/main/SSCECON209/2022h1/example%20dashboard.xlsx).

# Accessing Excel for free

You can access Microsoft Excel in multiple ways via UCR and UU:

1.  *(preferred)* Your UU student status grants you a free Office 365 license. To access it, go to [office.com](https://office.com) and log in with either your @ucr.nl or your @students.uu.nl email address and password. You can either use the online applications (Excel logo on the left sidebar) or install Office 365 on your desktop (“Install Office” button on the top right).
2.  You can also use UU’s MyWorkplace to access Excel and many other applications. Go to [solisworkspace.uu.nl](https://solisworkspace.uu.nl) and log in with your Solis-ID and password. Go to the “Apps” tab and look for “Excel 2019.” Click on the icon, and Excel will open on your desktop. If you are using this website for the first time, you will likely need to download Citrix receiver (if you need to, a the website will guide you through the process). When saving files, you should make sure to save your files on your local disc instead of the UU cloud - you can search for the approporiate folder by going to File -\> Save -\> Browse.

# Helpful links

## Excel basics

-   [Excel cheat sheet](https://www.customguide.com/cheat-sheet/excel-cheat-sheet.pdf)
-   [List of most important formulas](https://web.acd.ccac.edu/~ndowney/CIT140/Excel/Formulas.pdf)
-   [Full tutorial from opening Excel to making charts (video)](https://www.youtube.com/watch?v=e7xGuGqgp-Q)
-   [Cell referencing (video)](https://www.youtube.com/watch?v=Yx52CYvR5ao)
-   [Working with multiple sheets (video)](https://www.youtube.com/watch?v=4HdZx29SdoM)
-   [Excel Formulas and Functions Tutorial (video)](https://www.youtube.com/watch?v=Jl0Qk63z2ZY)

## Making figures in Excel

-   [Creating a chart step-by-step](https://www.excel-easy.com/data-analysis/charts.html)
-   [Creating a simple line chart (video)](https://www.youtube.com/watch?v=3o11OlLgYDo)
-   [Plotting multiple lines on one chart (video)](https://www.youtube.com/watch?v=YhmVVRwj3p8)
-   [Creating a scatterplot (video)](https://www.youtube.com/watch?v=OVA2M7EIx80)
-   [Customizing charts (video)](https://www.youtube.com/watch?v=TfkNkrKMF5c)
