---
layout: page
title: "SSCPOLI302<br> European Union Politics"
subtitle: "Fall 2024"
date: "Last updated: `r Sys.Date()`"
---

# Introduction

This page collects materials for the data-driven assignments in the Fall 2024 edition of EU Politics at UCR. You can also access the related files directly on [Github](https://github.com/ucrdatacenter/projects).

# First workshop: analysis of MEPs

The first Data Center workshop takes place on the Friday class of week 6 (4 October). You can find the workshop handout [here](SSCPOLI302_2024h2/workshop1.qmd). The same materials will be used during the Tuesday class of week 7 (8 October).

To prepare for the first workshop, please complete the preparatory instructions listed at the top of the workshop handout.

# Second workshop: analysis of legislative dossiers

The last Data Center workshop takes place on the Tuesday class of week 7 (15 October). You can find the workshop handout [here](SSCPOLI302_2024h2/workshop2.qmd).

To prepare for the workshop, please follow the preparatory instructions listed at the top of the workshop handout.

# Third workshop: further analysis of legislative dossiers

The last Data Center workshop takes place on the Friday class of week 7 (18 October). You can find the workshop handout [here](SSCPOLI302_2024h2/workshop3.qmd).

# Office hours

The Data Center offers office hours to help prepare for the workshops and complete the assignments. Please see the schedule [here](../../contact.qmd).
