---
layout: page
title: "AH-RHET101<br> Introduction to Rhetoric and Argumentation"
subtitle: "Spring 2025"
date: "Last updated: `r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, error=FALSE)
```

# Introduction

This page collects materials for the data-driven assignment in the Spring 2025 edition of Introduction to Rhetoric and Argumentation at UCR. You can also access the related files (data and R scripts) directly on [GitHub](https://github.com/ucrdatacenter/projects/tree/main/AH-RHET101/2025h1).

# Office hours

The Data Center offers office hours to help you with the data-driven assignments. You can find more information about the schedule [here](../../contact.qmd).

# Preparation for Data Center workshops

To participate in the workshops, you will need to have R and RStudio installed on your computer. If you don’t have these programs installed, please follow [this installation tutorial](../../tutorials/r_install.qmd).

In addition, the [R basics tutorial](../../../tutorials/r_basics.qmd) on the Data Center website explains the RStudio interface, and shows how to create a new project and how to install packages.

Please bring your fully charged laptop to all Data Center workshops.

# Workshop materials

## Workshops 1 (Digital Humanities) and 2 (Sketch Engine)

Please see the course Moodle page.

## Workshop 3: Introduction to R

Please find the workshop handout [here](AH-RHET101/workshop3.qmd).

## Homework assignment after workshop 3

Please open [this link](https://github.com/ucrdatacenter/projects/blob/main/AH-RHET101/2025h1/workshop3_homework.Rmd), and click on the "Download raw file" button (top right corner, with the downward pointing arrow). Save the file in your R project directory. Open the file in RStudio, and follow the instructions in the document to complete the assignment.

If you would like to have some more practice with the functions you learned during the 3rd workshop, you can find an optional homework assignment [here](https://github.com/ucrdatacenter/projects/blob/main/AH-RHET101/2025h1/workshop3_homework_optional.Rmd).

## Workshop 4: Sentiment analysis in R

Please find the workshop handout [here](AH-RHET101/workshop4.qmd).

## Homework assignment after workshop 4

Please open [this link](https://github.com/ucrdatacenter/projects/blob/main/AH-RHET101/2025h1/workshop4_homework.Rmd), and click on the "Download raw file" button (top right corner, with the downward pointing arrow). Save the file in your R project directory. Open the file in RStudio, and follow the instructions in the document to complete the assignment.
